# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Upload default translation to Tolgee

on:
  push:
    branches: [ "master" ]

jobs:
  job_check_strings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if strings.xml changed
        id: check_strings
        run: if [ $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep values/strings.xml | wc -l) -gt 0 ]; then echo "has_new_strings=1" > $GITHUB_OUTPUT; fi
        
  upload-translation:
    runs-on: ubuntu-latest
    needs: job_check_strings
    if: needs.check_strings.has_new_strings == 1
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Upload translations to Tolgee
      env:
         tolgee_token: ${{ secrets.tolgee_token }}
      run: |
        npm install @tolgee/cli
        export PATH=$PWD/node_modules/.bin:$PATH
        tolgee login "$tolgee_token"
        tolgee push
