# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Upload default translation to Tolgee

on:
  push:
    branches: [ "master" ]

jobs:
  check_strings:
    runs-on: ubuntu-latest
    outputs:
      has_new_strings: ${{ steps.check_strings.outputs.has_new_strings }}
    steps:
      # https://stackoverflow.com/a/77036975
      - name: Calculate fetch-depth
        id: pre-checkout
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            COUNT=$(( $(echo "$COMMITS" | jq length) + 1 ))
          else
            COUNT=1
          fi
          echo "fetch-depth=$COUNT" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ steps.pre-checkout.outputs.fetch-depth }}
      - name: Check if strings.xml changed
        id: check_strings
        run: |
          if [ $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep values/strings.xml | wc -l) -gt 0 ]; then 
             echo "This push has changes to strings.xml. Pushing new translations..."
             echo "has_new_strings=true" >> "$GITHUB_OUTPUT"
          fi
      - name: check again
        run: echo "${{ steps.check_strings.outputs.has_new_strings }}"

  upload-translation:
    runs-on: ubuntu-latest
    needs: check_strings
    if: needs.check_strings.outputs.has_new_strings == 'true'
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Upload translations to Tolgee
      env:
         tolgee_token: ${{ secrets.tolgee_token }}
      run: |
        npm install @tolgee/cli
        export PATH=$PWD/node_modules/.bin:$PATH
        tolgee login "$tolgee_token"
        tolgee push
